### ISSUE TITLE
Why are the 4-liner poems made into 2-liners?

### ISSUE THREAD

**Issue by Andhrabharati** [funderburkjim/boesp-prep-ab#1]
As I have been seeing all through my life, it is the general practice to join two lines of a poem (वृत्त  or other type)-- only if it is less than 12/13 letters per quarter.

Otherwise they go by the rule 'poems in quarters - 4 पादs', except one particular type dvipada, which has only two पादs.

Any specific reason for your making them all as 2-liners?

**Comment by Andhrabharati** [comment]
Shall I split them as per the print while proofing, or keep them as is?

**Comment by funderburkjim** [comment]
Split them.

We currently have no markup for these cases.

Will have to develop one based on your observations.

Please make a list of the items numbers and page  as you notice them.

This list, and your line breaks, will allow introduction of some markup (maybe just a `<br/>` tag) to
indicate this.

**Comment by Andhrabharati** [comment]
I already did about half of the file.

I had split the lines with //, which is the practice for me to indicate line breaks.
