### ISSUE TITLE
Letter followed by number in 15 lines

### ISSUE THREAD

**Issue by Andhrabharati** [funderburkjim/boesp-prep-ab#2]
There are 15 such lines-

	Line 23:     अकस्मात्प्रक्रिया नृ२णामकस्माच्चापकर्षणम् ।
	Line 512: +   <s>अत एव विवेक्तॄ२णां</s> s. nach Spruch <s>वृत्तिं स्वां बहु मन्यते</s>.
	Line 1776:     अपि प्राणसमानिष्टान्पालितां२ल्लालितानपि ।
	Line 2203:     अमृतपायिनां नृ२णां संतोषो नैव जायते ।
	Line 2231: +   <s>अमृताप्यायिनां नृ२णाम्</s> s. Spruch 531.
	Line 2237:     देवतानां पितृ२णां च भागो येन प्रदीयते ॥
	Line 3799:     देवान्पितृ२न्समभ्यर्च्य खादन्मांसं न दोषभाक् ॥
	Line 5241:     पदवीमुपकर्तृ२णां यान्ति निश्चेतना अपि ॥
	Line 5282:     उपदेशप्रदातृ२णां नराणां हितमिच्छताम् ।
	Line 5286: +   <s>उपदेशेपदातृ२णाम्</s> s. Spruch 1285.
	Line 5291: +   <s>उपदेशोपदातृ२णाम्</s> s. Spruch 1285.
	Line 5346:     सहम्रं तु पितृ२न्माता गौरवेणातिरिच्यते ॥
	Line 7751:     हर्षं संजनयन्नृ२णां स राज्ञो धर्म उच्यते ॥
	Line 8335:     ऋ१ते वर्षान्न कौन्तेय जातु निर्वतेयेत्फलम् ॥
	Line 8722:     अर्थसंचयकर्तृ२णि भाग्यानि पृथगेव हि ॥

would you like to correct your conversion for these? (preferred way, and useful for future exercises as well)
or just want me to go ahead correcting them in proofing?

**Comment by Andhrabharati** [comment]
also there are 43 _ (underscore) characters in the file.

**Comment by funderburkjim** [comment]
I'll correct this.  It is an Error in HK coding in the 'utf8' version.
Have corrected.  Will be present in your revised file.
