### ISSUE TITLE
10 strings inside <s>...</s> unconverted

### ISSUE THREAD

**Issue by Andhrabharati** [funderburkjim/boesp-prep-ab#3]
Line 437: +   <s>अजायुद्धमृषिश्राद्धं, अजायुद्धं मुनिश्राद्धं</s> u. <s>ajAyuddhe dvijazrAddhe</s> s. den vorangehenden Spruch.
	Line 965: +   <s>अधीतव्यवहाराङ्गम् (°व्यवहारार्थम्)</s> s. nach Spruch <s>svadezajaM kulAcAra°</s>.
	Line 2162: +   <s>अमित्रं कुरुते मित्रं वीर्या°</s> s. Spruch <s>yo 'mitraM kurute mitraM vIryA°</s>.
	Line 5272: +   <s>उपकरं करोम्यस्य</s> s. Spruch <s>mayAsyopakRtaM pUrvam. upakArAcca lokAnAm</s> s. Spruch <s>द्रवत्वात्सर्वलोहानाम्_</s>
	Line 5290: +   <s>उपगृह्य तु वैराणि</s> s. nach Spruch <s>nahi vairANi zAmyanti. upacaritavyAH</s> s. Spruch <s>ऽवरिचरितव्याः_</s>
	Line 6053: +   <s>एवमेव कुले जाताः</s> s. Spruch 69. <s>एवमेव मनुष्याणाम्</s> s. nach Spruch <s>यथा ग्रामान्तरं गच्छन्_</s> <s>एवं पूर्वैर्गतो मार्गः</s> s. Spruch <s>yathA hi sArthaM gacchantam.</s>
	Line 6220: +   <s>कथम्चिदह्नि हृदये</s> s. nach Spruch <s>rAjanrAjanyupAdhyAyaH. kathaM tvayA na sevyante</s> s. den folgenden Spruch.
	Line 7083: +   <s>किं कन्दर्प करं, वल</s> d. i.<s>बल, कुल, यव, वकुल</s> d. i.<s>बकुल, कुवलय_) किं कन्दर्प करं कदर्थयसि</s> s. Spruch <s>re kandarpa karaM kadarthayasi.</s>
	Line 8044: +   <s>क्रमगतो हितमतिः (हितमानी)</s> s. Spruch <s>mdhavI vAkpaTuH prAjJaH. kramAdvetasavRttiH san</s> s. Spruch <s>समाक्रान्तो बलवता_</s>
	Line 8441: +   <s>गच्छ शूकर (सूकर) भद्रं ते</s> s. Spruch <s>dazavyAghrA jitAH pUrvam.</s>

**Comment by funderburkjim** [comment]
Have corrected this locally.  It was due to my mis-understanding of a Python regular expression substitution across line breaks.
