### ISSUE TITLE
any correction in encoding needed?

### ISSUE THREAD

**Issue by Andhrabharati** [funderburkjim/boesp-prep-ab#5]
; 373 : page 1.68

utf8: tAdRgyAdRghyuttaptavAlukAnikaraH
slp1: tAdfgyAdfGyuttaptavAlukAnikaraH

actual devanagari: तादृग्यादृग्‍ह्युत्तप्तवालुकानिकरः

**Comment by funderburkjim** [comment]
I don't see a problem with the conversion from HK  (which is the encoding of the utf8) text, and the slp1.
The programmatic conversion to deva is तादृग्यादृघ्युत्तप्तवालुकानिकरः  and I don't see a problem there.

I guess the problem you are mentioning is with the 'gh' in HK.   HK has several problems, and this is one of
them.  In HK, two letters 'gh' are required to get the aspirated 'g'.   In this case,  the real desideratum is to
represent two consonants 'g' followed by 'h'.   There is no way to do this in (standard) HK.

So, what you should do is correct the Devanagari.
Then I will convert this back to slp1,  and there will be no loss there  ('gh' in SLP1),  

but, there is would be a problem if we convert back to HK.  I'll have to find some workaround from standard HK
to deal with this when the time comes.

Please indicate other such flaws as you notice.  This will help me with the workaround.

**Comment by Andhrabharati** [comment]
yes, I am talking about encoding issue here, not conversion.

I already corrected the devanagari word, as posted above.

**Comment by Andhrabharati** [comment]
This issue seems not yet resolved.

**Comment by funderburkjim** [comment]
Just to emphasize,  this is not an issue for slp1 and deva.

I will have to deal with it if and when we go to transcode back to HK that Thomas is working with.

But it doesn't affect your work with Sanskrit verses, except that you will have to get the Devanagari right, as you
are no doubt already doing.

**Comment by Andhrabharati** [comment]
got it.
