### ISSUE TITLE
Fix of initial problems 

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep-ab#6]
@Andhrabharati   Am working on correcting the systematic problems you noticed.
Will aim to finish the corrections tomorrow.
Please wait until I notify this correction work done before beginning your proof corrections.

**Comment by Andhrabharati** [comment]
Beginning? I already crossed half-way, as mentioned in response in another issue (a while back.)

**Comment by Andhrabharati** [comment]
I am just indicating the issues as I identify, just to make you aware of them (for future works), not waiting for your correction (for the present work).

**Comment by funderburkjim** [comment]
boesp-1_deva_rev.txt incorporates my response to issues 1-5.

**Comment by Andhrabharati** [comment]
is the issue-5 : "HK gh g_h differentiation" resolved?

the revised deva.txt file is still with gh only, not g_h.

**Comment by funderburkjim** [comment]
There is no way to know when 'gh' in HK is used to represent a single aspirated 'g', or a conjunct consonant.

Similarly with any  of the aspirated consonants  (which all are two-letter xh in [HK](https://en.wikipedia.org/wiki/Harvard-Kyoto)).

There is also the hiatus problem with HK  ('ai' and 'au').

If we insist on having invertibility between HK and SLP1 transliterations in ind. spr., then we'll have to develop
a consistent extension to HK.  'g_h', 'a_i' might work.

Fortunately, all these problems are rare.

**Comment by Andhrabharati** [comment]
@funderburkjim 

As this is not a candidate for another issue, just posting here.

I had finished my proofing work about 5-6 days back itself; but not pushed the file as Sampada hasn't done her part yet, for you to compare both versions.

Do you want me to post my file anyway?

**Comment by funderburkjim** [comment]
> Do you want me to post my file anyway?

@Andhrabharati  --  Ok for you to post whenever you like , within the boesp-prep-ab respository.

BTW,  you offered  in another issue comment  to proof the Sanskrit text in the footnotes and corrections sections.   We need to wait until Thomas finishes his work on vols 1-3 before you begin that work.  When
Thomas' work is done, and we have a stable utf8 version,  then will be the time.  Estimate this will be in a few weeks.

**Comment by Andhrabharati** [comment]
As you are "sounding" that there is no use for it any sooner (until Sampada does her part), I am not posting my file now. (Will do it, once she completes her work.)

**Comment by Andhrabharati** [comment]
Taking the advantage of my work done before Sampada's, I had compared my work against her commits all these days.

She indeed has done a good job (but has few errors still).

@funderburkjim would anyway be comparing my work and her's finally.

I would request him to post the comparison in both slp1 and Devanagari, so that we each know how to improve the working further.

And here is my file-
[boesp-1_deva_AB (11th Sep).txt](https://github.com/funderburkjim/boesp-prep-ab/files/7574203/boesp-1_deva_AB.11th.Sep.txt)

**Comment by funderburkjim** [comment]
@Andhrabharati   OK Thanks.  Hope to get to comparison of the two versions in the coming days.

Will also be preparing the volume 2 verses soon.
