### ISSUE TITLE
Boesp volume 2

### ISSUE THREAD

**Issue by funderburkjim** [funderburkjim/boesp-prep-ab#7]
Volume 2 of Boehtlingk's sayings is now ready for @Andhrabharati .

Do a git pull, and work with [boesp-2_deva.txt](https://github.com/funderburkjim/boesp-prep-ab/blob/main/sanproof/boesp-2_deva.txt)

The pdf is available at: https://sanskrit-lexicon.uni-koeln.de/scans/BOESPScan/pdfs/boesp-2.pdf  (about 110MB).

Procedure is same as before.  But,  this time do not consider the space before avagraha as error - just leave those spaces.

I changed my mind, and now think we should leave the spaces before avagraha, as used
by the author.  I'll reintroduce the spaces in the volume 1 verses when the time comes.

**Comment by Andhrabharati** [comment]
The beginning verses 2220-3 should be with page 2.1, not page 1.435!

**Comment by Andhrabharati** [comment]
@funderburkjim 

A page break after the verse(s) was earlier (boesp-1) on the same line, also in all the other cologne texts; but in this boesp-2, it is put on a next line.

Any specific reason for this change?

**Comment by Andhrabharati** [comment]
There are few places where avagraha is not preceded by a space. (of course, could be corrected while proofing)

**Comment by funderburkjim** [comment]
Regarding page break errors:

I was aware of flaws in the 'page' parameter, and debated whether to just omit it from this document.
This 1.435 occurs because `[Seite1.435]`  occurs in the text at the end of  preceding verse 2219.
(Search for 'D2219' in [boesp_20.txt](https://raw.githubusercontent.com/funderburkjim/boesp-prep/main/step0/changes/boesp_20.txt), which is the version from which these volume 2 verses were extracted)

I was hoping such problems would not interfere with the proofreading task.


As to  whether the `[Seite]` appears at end of a line or on a separate line, there is currently no 'rule'.  Would
prefer you not to change the position of the Seite.


@sanskritisampada  -- hope you see this comment also,

**Comment by Andhrabharati** [comment]
> I was hoping such problems would not interfere with the proofreading task.

yes, they would be corrected while proofing.

> Would prefer you not to change the position of the Seite.

Sure, will keep this in mind.

[I will be taking up the work after 2-3 days; just browsed through the text cursorily once. ]
